<?php

$this->startSetup();

$this->run("INSERT INTO `cms_block` ( `title`, `identifier`, `content`, `creation_time`, `update_time`, `is_active`)
VALUES
	( 'Company info links', 'company-info-links', '<ul>\r\n<li><a href=\"about-us\">About us</a></li>\r\n<li><a href=\"pearl%20buying%20tips\">Pearl buying tips</a></li>\r\n<li><a href=\"gift%20and%20message%20card%20service\">Gift and message card service</a></li>\r\n<li><a href=\"/testimonials\">testimonials</a></li>\r\n<li><a href=\"/certificate-of-authenticity\">certificate of authenticity</a></li>\r\n<li><a href=\"/contact-us\">contact us</a></li>\r\n<li><a href=\"/blog\">the blog</a></li>\r\n</ul>', '2014-09-08 16:15:27', '2014-09-08 16:15:27', 1),
	( 'Home Banner', 'home-banner', '<p><img title=\"main banner\" src=\"{{media url=\"wysiwyg/home/main-banner.png\"}}\" alt=\"home bannner\" /></p>', '2014-09-08 19:15:38', '2014-09-08 19:16:09', 1),
	( 'Customer Services Links', 'customer-services-links', '<ul>\r\n<li><a href=\"/t-and-c\">T&amp;C&rsquo;s</a></li>\r\n<li><a href=\"/online-ordering-and-security\">Online ordering &amp; security</a></li>\r\n<li><a href=\"/delivery\">Delivery</a></li>\r\n<li><a href=\"/returns\">Returns</a>&nbsp;</li>\r\n<li><a href=\"/privacy\">Privacy</a>&nbsp;</li>\r\n<li><a href=\"/cookies\">Cookies</a></li>\r\n<li><a href=\"caring-for-your-pearls\">Caring for your pearls</a></li>\r\n<li><a href=\"/pearl-restringing-service\">Pearl re-stringing service</a></li>\r\n</ul>', '2014-09-08 21:01:32', '2014-09-08 21:01:32', 1),
	( 'Contact Us Links', 'contact-us-links', '<p class=\"p1\"><span class=\"s2\">e.</span><a href=\"mailto:service@absolutepearls.co.uk\"><span class=\"s1\"> service@absolutepearls.co.uk</span></a></p>\r\n<p class=\"p4\"><span class=\"s1\"><br /></span></p>\r\n<p class=\"p4\"><span class=\"s1\">t. </span><span class=\"s3\"><strong>0151 625 7688</strong></span><span class=\"s1\"> daily 8am-8pm&nbsp;</span></p>\r\n<p class=\"p5\"><span class=\"s1\">m. </span><span class=\"s3\"><strong>07803 172 096</strong></span><span class=\"s1\"> at any time</span></p>\r\n<ul>\r\n<li><a class=\"facebook\" href=\"facebook\">facebook</a></li>\r\n<li><a class=\"twitter\" href=\"twitter\">twitter</a></li>\r\n<li><a class=\"google\" href=\"google\">google</a></li>\r\n<li><a class=\"pinterest\" href=\"pinterest\">pinterest</a></li>\r\n<li><a class=\"instagram\" href=\"instagram\">instagram</a>&nbsp;</li>\r\n</ul>\r\n<p><a href=\"http://absoluteblog.com\">absoluteblog.com</a></p>', '2014-09-08 21:30:21', '2014-09-09 14:45:51', 1),
	( 'Security Icons', 'security-icons', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"{{media url=\"wysiwyg/home/security-icons.png\"}}\" alt=\"\" /></p>', '2014-09-08 21:35:09', '2014-09-08 21:35:09', 1);


	
DELETE FROM `cms_page` where `title` = 'Home Page';

INSERT INTO `cms_page` (`page_id`, `title`, `root_template`, `meta_keywords`, `meta_description`, `identifier`, `content_heading`, `content`, `creation_time`, `update_time`, `is_active`, `sort_order`, `layout_update_xml`, `custom_theme`, `custom_root_template`, `custom_layout_update_xml`, `custom_theme_from`, `custom_theme_to`)
VALUES
	(2, 'Home page', 'Webtise_Absolutepearls_home', NULL, NULL, 'home', NULL, '<h1 class=\"p1\">GENUINE CULTURED PEARL JEWELERY<span class=\"underline\">&nbsp;</span></h1>\r\n<p class=\"p2\"><span class=\"s2\">Cultured pearl jewellery - ideal bridal &amp; wedding jewellery, birthday and wedding anniversary pearl related gift ideas, informal and formal pearl jewellery gifts... our pearl jewellery ranges from stunning cultured pearl earrings to that little pink pearl necklace and matching pearl bracelet that you always fancied.</span></p>\r\n<p class=\"p3\">All our pearl jewellery features genuine cultured pearls, whether it be a cultured pearl necklace, pearl earrings, or a cultured pearl bracelet that you chose as a gift for your loved one. If you find a pearl necklace or pearl bracelet is too long, just specify the length of necklace or bracelet that you require. If you would like a pearl necklace or pearl bracelet custom made, just ask Absolute Pearls, the pearl jewellery specialist.</p>', '2014-09-08 11:18:04', '2014-09-17 11:02:16', 1, 0, '<!--<reference name=\"content\">\r\n        <block type=\"catalog/product_new\" name=\"home.catalog.product.new\" alias=\"product_new\" template=\"catalog/product/new.phtml\" after=\"cms_page\">\r\n            <action method=\"addPriceBlockType\">\r\n                <type>bundle</type>\r\n                <block>bundle/catalog_product_price</block>\r\n                <template>bundle/catalog/product/price.phtml</template>\r\n            </action>\r\n        </block>\r\n        <block type=\"reports/product_viewed\" name=\"home.reports.product.viewed\" alias=\"product_viewed\" template=\"reports/home_product_viewed.phtml\" after=\"product_new\">\r\n            <action method=\"addPriceBlockType\">\r\n                <type>bundle</type>\r\n                <block>bundle/catalog_product_price</block>\r\n                <template>bundle/catalog/product/price.phtml</template>\r\n            </action>\r\n        </block>\r\n        <block type=\"reports/product_compared\" name=\"home.reports.product.compared\" template=\"reports/home_product_compared.phtml\" after=\"product_viewed\">\r\n            <action method=\"addPriceBlockType\">\r\n                <type>bundle</type>\r\n                <block>bundle/catalog_product_price</block>\r\n                <template>bundle/catalog/product/price.phtml</template>\r\n            </action>\r\n        </block>\r\n    </reference>\r\n    <reference name=\"right\">\r\n        <action method=\"unsetChild\"><alias>right.reports.product.viewed</alias></action>\r\n        <action method=\"unsetChild\"><alias>right.reports.product.compared</alias></action>\r\n    </reference>-->', NULL, NULL, NULL, NULL, NULL);

");

$this->endSetup();