<?php
$i = 0;
$_columnCount = 4;
$products = $this->getProducts();
$_helper = $this->helper('catalog/output');
if(count($products) > 6): ?>

<div class="featured_products">
	<h2>This week we love ...</h2>
	<a href="#" class="next-link">Next</a>
	<a href="#" class="prev-link">Next</a>
<ul class="products-grid">
<?php foreach($products as $_product):
	
	$_product = Mage::getModel('catalog/product')->load($_product->getId());
?>

<?php if ($i++%$_columnCount==0): ?>
            <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 300; ?>
                    
                    <?php 
                    $product = Mage::getModel("catalog/product")->load($_product->getId());
                    foreach($product->getMediaGalleryImages() as $image){
                    	
                    	if($image->getData('position') == 2){
                    	    $hoverimage = $image;
                    	};
                    }; 
                    ?>

                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                          hover="<?php echo $hoverimage->getData("url");?>"
                          default="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         class="product-list-image"/>
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a></h2>
					<?php if($_product->isSaleable()): ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('- IN STOCK -') ?></span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('- OUT OF STOCK -') ?></span></p>
                        <?php endif; ?>
                    <?php
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach($_nameAfterChildren as $_nameAfterChildName):
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                    ?>
                        <?php echo $_nameAfterChild->toHtml(); ?>
                    <?php endforeach; ?>

                    <?php echo $this->getPriceHtml($_product, true) ?>
                   
                 </div>
            </li>
<?php endforeach; ?>


</ul>
<div class="clear"></div>
</div>
<?php endif; ?>