<?php  
$_categories = $this->getMainChldCategories();
?>

<div class="category-grid">
<?php $i=0; foreach ($_categories as $_category): ?>

<?php
    $layer = Mage::getSingleton('catalog/layer');
    $layer->setCurrentCategory(Mage::getModel('catalog/category')->load($_category->getId()));
    $helper = Mage::helper('catalog/category');
?>
    <div class="category <?php if($i % 3 == 0){ echo ' first'; } if($i >= 3){ echo ' additional-rows'; }?>">
    	<div class="content">
	        <?php $_img = $this->getCurrentCategory()->getImageUrl() ?>
	        <?php if($_img): ?>
	            <div class="category-img">
	                <a href="<?php echo $helper->getCategoryUrl($_category);?>">
	                    <img src="<?php echo $_img?>" title="<?php echo $_category->getName() ?>"/>
	                </a>
	            </div>
	        <?php endif; ?>
	        <div class="category-name<?php if (strlen($_category->getName()) > 32) echo ' small-category-name' ?>">
	            <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
	            <?php echo $this->htmlEscape($_category->getName()) ?>
	            </a>
	        </div>
	         <div class="category-description">
	            <?php echo $this->htmlEscape($this->getCurrentCategory()->getDescription()) ?>
	        </div>
        </div>
    </div>
<?php
    $i++;
    endforeach;
?>

</div>

<?php $_subcategories = $this->getSubChldCategories();
?>
<div class="category-sub-grid">
<?php $i=0; foreach ($_subcategories as $_category): ?>

<?php
    $layer = Mage::getSingleton('catalog/layer');
    $layer->setCurrentCategory(Mage::getModel('catalog/category')->load($_category->getId()));
    $helper = Mage::helper('catalog/category');
?>
    <div class="category <?php if($i % 3 == 0){ echo ' first'; } if($i >= 3){ echo ' additional-rows'; }?>">
    	<div class="content">
	        <?php $_img = $this->getCurrentCategory()->getImageUrl() ?>
	        <?php if($_img): ?>
	            <div class="category-img">
	                <a href="<?php echo $helper->getCategoryUrl($_category);?>">
	                    <img src="<?php echo $_img?>" title="<?php echo $_category->getName() ?>"/>
	                </a>
	            </div>
	        <?php endif; ?>
	        <div class="category-name<?php if (strlen($_category->getName()) > 32) echo ' small-category-name' ?>">
	            <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
	            <?php echo $this->htmlEscape($_category->getName()) ?>
	            </a>
	        </div>
        </div>
    </div>
<?php
    $i++;
    endforeach;
?>
</div>

<?php
$i = 0;
$_columnCount = 4;
$products = $this->getProducts();
$_helper = $this->helper('catalog/output');
?>
<div class="slider">
<div class="featured_category_products">
	<h2>Our Most Wanted ...</h2>
	<a href="#" class="next-link">Next</a>
	<a href="#" class="prev-link">Prev</a>
<ul class="products-grid">
<?php  foreach($products as $_product):
	
	$_product = Mage::getModel('catalog/product')->load($_product->getId());
?>

<?php if ($i++%$_columnCount==0): ?>

<?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 300; ?>
                    
                    <?php 
                    $product = Mage::getModel("catalog/product")->load($_product->getId());
                   
                    ?>

                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                          default="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         class="product-list-image"/>
                </a>
               <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
					<?php if($_product->isSaleable()): ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('- IN STOCK -') ?></span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('- OUT OF STOCK -') ?></span></p>
                        <?php endif; ?>
                    <?php
                        /*$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach($_nameAfterChildren as $_nameAfterChildName):
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                    ?>
                        <?php echo $_nameAfterChild->toHtml(); ?>
                    <?php endforeach; */?>

                    <?php // echo $this->getPriceHtml($_product, true) ?>
                   
                 </div>
            </li>
<?php  endforeach;  ?>

</ul>
</div>
</div>