hello im a template 

<?php/*  $_categories = $this->getCurrentChildCategories() ?>
<?php // $_collectionSize = $_categories->count() ?>

<div class="subcategory-grid">
<?php $i=0; foreach ($_categories as $_category): ?>

<?php
    $layer = Mage::getSingleton('catalog/layer');
    $layer->setCurrentCategory(Mage::getModel('catalog/category')->load($_category->getId()));
    $helper = Mage::helper('catalog/category');
?>
    <div class="category-container<?php if($i % 3 == 0){ echo ' first'; } if($i >= 3){ echo ' additional-rows'; }?>">
        <?php $_img = $this->getCurrentCategory()->getImageUrl() ?>
        <?php if($_img): ?>
            <div class="category-img">
                <a href="<?php echo $helper->getCategoryUrl($_category);?>">
                    <img src="<?php echo $_img?>" title="<?php echo $_category->getName() ?>"/>
                </a>
            </div>
        <?php endif; ?>
        <div class="category-name<?php if (strlen($_category->getName()) > 32) echo ' small-category-name' ?>">
            <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
            <?php echo $this->htmlEscape($_category->getName()) ?>
            </a>
        </div>
    </div>
<?php
    $i++;
    endforeach;
?>
</div>