<footer>
	<div class="main">
	 <div class="wrapper">
	 	<div class="mobile-acordion">
		<div class="company-info">
			<div class="content">
				<h4>Company info</h4>
			    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('company-info-links')->toHtml(); ?>
			</div>
		</div>
		<div class="customer-services">
			<div class="content">
			    <h4>Customer Services</h4>
			    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer-services-links')->toHtml(); ?>
			</div>
		</div>
		</div>
		<div class="contact-us">
			<div class="content">
			<h4>How to contact us</h4>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-us-links')->toHtml(); ?>
			</div>
		</div>
		<div class="newsletter">
			<div class="content">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('newsletter-footer')->toHtml(); ?>
			<form>
				<input type="email" name="" placeholder="Email Address"/>
				<input type="submit" value="Sign up!" />
			</form>
			</div>
		</div>
	 </div>
	 <div class="clear"></div>
	</div>
	
	<div class="security">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('security-icons')->toHtml(); ?>
	</div>
	<div class="copyright">
		
		<p>Registered under the Data Protection Act 1998. Number Z829313X</br>
		All prices include UK VAT | Absolute Pearls © 2014  |  Web Design by<a href="http://www.webtise.com"> Webtise </a> </p>
	</div>
</footer>